[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/xyk',
    'runtime',
]
[patch."https://github.com/mangata-finance/substrate"]
frame-metadata = { path = "../substrate/frame/metadata" }
pallet-authorship = { path = "../substrate/frame/authorship" }
pallet-transaction-payment-rpc-runtime-api = { path = "../substrate/frame/transaction-payment/rpc/runtime-api" }
pallet-transaction-payment-rpc = { path = "../substrate/frame/transaction-payment/rpc" }
pallet-transaction-payment = { path = "../substrate/frame/transaction-payment" }
frame-system-rpc-runtime-api = { path = "../substrate/frame/system/rpc/runtime-api" }
frame-system = { path = "../substrate/frame/system" }
frame-benchmarking = { path = "../substrate/frame/benchmarking" }
pallet-session = { path = "../substrate/frame/session" }
pallet-balances = { path = "../substrate/frame/balances" }
pallet-authority-discovery = { path = "../substrate/frame/authority-discovery" }
pallet-random-seed = { path = "../substrate/frame/random-seed" }
frame-executive = { path = "../substrate/frame/executive" }
pallet-treasury = { path = "../substrate/frame/treasury" }
pallet-sudo = { path = "../substrate/frame/sudo" }
pallet-offences = { path = "../substrate/frame/offences" }
pallet-grandpa = { path = "../substrate/frame/grandpa" }
pallet-collective = { path = "../substrate/frame/collective" }
pallet-randomness-collective-flip = { path = "../substrate/frame/randomness-collective-flip" }
frame-support = { path = "../substrate/frame/support" }
frame-support-procedural-tools-derive = { path = "../substrate/frame/support/procedural/tools/derive" }
frame-support-procedural-tools = { path = "../substrate/frame/support/procedural/tools" }
frame-support-procedural = { path = "../substrate/frame/support/procedural" }
pallet-staking = { path = "../substrate/frame/staking" }
pallet-staking-reward-curve = { path = "../substrate/frame/staking/reward-curve" }
pallet-finality-tracker = { path = "../substrate/frame/finality-tracker" }
pallet-babe = { path = "../substrate/frame/babe" }
pallet-timestamp = { path = "../substrate/frame/timestamp" }
pallet-elections-phragmen = { path = "../substrate/frame/elections-phragmen" }
sc-informant = { path = "../substrate/client/informant" }
sc-finality-grandpa = { path = "../substrate/client/finality-grandpa" }
sc-executor-wasmtime = { path = "../substrate/client/executor/wasmtime" }
sc-executor-common = { path = "../substrate/client/executor/common" }
sc-executor-wasmi = { path = "../substrate/client/executor/wasmi" }
sc-executor = { path = "../substrate/client/executor" }
sc-network-gossip = { path = "../substrate/client/network-gossip" }
sc-transaction-graph = { path = "../substrate/client/transaction-pool/graph" }
sc-transaction-pool = { path = "../substrate/client/transaction-pool" }
sc-tracing = { path = "../substrate/client/tracing" }
sc-client-db = { path = "../substrate/client/db" }
extrinsic-shuffler = { path = "../substrate/client/shuffler" }
sc-network = { path = "../substrate/client/network" }
sc-authority-discovery = { path = "../substrate/client/authority-discovery" }
sc-keystore = { path = "../substrate/client/keystore" }
sc-rpc-server = { path = "../substrate/client/rpc-servers" }
sc-light = { path = "../substrate/client/light" }
sc-client-api = { path = "../substrate/client/api" }
sc-rpc = { path = "../substrate/client/rpc" }
sc-service = { path = "../substrate/client/service" }
sc-block-builder = { path = "../substrate/client/block-builder" }
sc-rpc-api = { path = "../substrate/client/rpc-api" }
sc-chain-spec-derive = { path = "../substrate/client/chain-spec/derive" }
sc-chain-spec = { path = "../substrate/client/chain-spec" }
sc-proposer-metrics = { path = "../substrate/client/proposer-metrics" }
sc-peerset = { path = "../substrate/client/peerset" }
sc-basic-authorship = { path = "../substrate/client/basic-authorship" }
sc-offchain = { path = "../substrate/client/offchain" }
sc-state-db = { path = "../substrate/client/state-db" }
sc-consensus = { path = "../substrate/client/consensus/common" }
sc-consensus-uncles = { path = "../substrate/client/consensus/uncles" }
sc-consensus-epochs = { path = "../substrate/client/consensus/epochs" }
sc-consensus-slots = { path = "../substrate/client/consensus/slots" }
sc-consensus-babe = { path = "../substrate/client/consensus/babe" }
sc-cli = { path = "../substrate/client/cli" }
sc-telemetry = { path = "../substrate/client/telemetry" }
fork-tree = { path = "../substrate/utils/fork-tree" }
frame-benchmarking-cli = { path = "../substrate/utils/frame/benchmarking-cli" }
substrate-frame-rpc-system = { path = "../substrate/utils/frame/rpc/system" }
substrate-build-script-utils = { path = "../substrate/utils/build-script-utils" }
substrate-prometheus-endpoint = { path = "../substrate/utils/prometheus" }
substrate-wasm-builder-runner = { path = "../substrate/utils/wasm-builder-runner" }
substrate-test-utils-derive = { path = "../substrate/test-utils/derive" }
substrate-test-utils = { path = "../substrate/test-utils" }
sp-panic-handler = { path = "../substrate/primitives/panic-handler" }
sp-encrypted-tx = { path = "../substrate/primitives/encrypted-tx" }
sp-inherents = { path = "../substrate/primitives/inherents" }
sp-authorship = { path = "../substrate/primitives/authorship" }
sp-storage = { path = "../substrate/primitives/storage" }
sp-std = { path = "../substrate/primitives/std" }
sp-finality-grandpa = { path = "../substrate/primitives/finality-grandpa" }
sp-ignore-tx = { path = "../substrate/primitives/ignore-tx" }
sp-version = { path = "../substrate/primitives/version" }
sp-transaction-pool = { path = "../substrate/primitives/transaction-pool" }
sp-tracing = { path = "../substrate/primitives/tracing" }
sp-database = { path = "../substrate/primitives/database" }
sp-debug-derive = { path = "../substrate/primitives/debug-derive" }
extrinsic-info-runtime-api = { path = "../substrate/primitives/extrinsic-info-runtime-api" }
sp-session = { path = "../substrate/primitives/session" }
sp-core = { path = "../substrate/primitives/core" }
sp-keyring = { path = "../substrate/primitives/keyring" }
sp-authority-discovery = { path = "../substrate/primitives/authority-discovery" }
sp-utils = { path = "../substrate/primitives/utils" }
sp-runtime-interface-proc-macro = { path = "../substrate/primitives/runtime-interface/proc-macro" }
sp-runtime-interface = { path = "../substrate/primitives/runtime-interface" }
sp-arithmetic = { path = "../substrate/primitives/arithmetic" }
sp-api-proc-macro = { path = "../substrate/primitives/api/proc-macro" }
sp-api = { path = "../substrate/primitives/api" }
sp-rpc = { path = "../substrate/primitives/rpc" }
sp-state-machine = { path = "../substrate/primitives/state-machine" }
sp-block-builder = { path = "../substrate/primitives/block-builder" }
sp-wasm-interface = { path = "../substrate/primitives/wasm-interface" }
sp-npos-elections-compact = { path = "../substrate/primitives/npos-elections/compact" }
sp-npos-elections = { path = "../substrate/primitives/npos-elections" }
sp-application-crypto = { path = "../substrate/primitives/application-crypto" }
sp-serializer = { path = "../substrate/primitives/serializer" }
sp-chain-spec = { path = "../substrate/primitives/chain-spec" }
sp-offchain = { path = "../substrate/primitives/offchain" }
sp-staking = { path = "../substrate/primitives/staking" }
sp-trie = { path = "../substrate/primitives/trie" }
sp-blockchain = { path = "../substrate/primitives/blockchain" }
sp-allocator = { path = "../substrate/primitives/allocator" }
sp-externalities = { path = "../substrate/primitives/externalities" }
sp-finality-tracker = { path = "../substrate/primitives/finality-tracker" }
sp-consensus = { path = "../substrate/primitives/consensus/common" }
sp-consensus-slots = { path = "../substrate/primitives/consensus/slots" }
sp-consensus-vrf = { path = "../substrate/primitives/consensus/vrf" }
sp-consensus-babe = { path = "../substrate/primitives/consensus/babe" }
sp-timestamp = { path = "../substrate/primitives/timestamp" }
sp-runtime = { path = "../substrate/primitives/runtime" }
sp-io = { path = "../substrate/primitives/io" }
