[package]
authors = ['Mangata team']
name = "proof-of-stake-rpc"
version = "2.0.0"
edition = "2018"
description = "RPC calls for Proof of Stake"
license = "GPL-3.0-or-later"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.16.2", features = ["server", "client", "macros"] }
serde = { version = "1.0.126", features = ["derive"], optional = true }

# Substrate packages

sp-api = { version = '4.0.0-dev', default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-blockchain = { version = '4.0.0-dev', default-features = false, git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-rpc = { version = '6.0.0', default-features = false, git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-core = { version = '7.0.0', default-features = false, git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-std = { version = '5.0.0', default-features = false, git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-runtime = { version = '7.0.0', default-features = false, git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }

# local packages

proof-of-stake-runtime-api = { version = "2.0.0", path = "../runtime-api", default-features = false }

[features]
default = ["std"]
std = [
    "serde",
    "sp-api/std",
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    "proof-of-stake-runtime-api/std"
]
