[settings]
timeout = 1000
bootnode = false

[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
chain = "rococo-local"

[relaychain.genesis.runtime.runtime_genesis_config.configuration.config]
  max_validators_per_core = 2
  needed_approvals = 2
  [[relaychain.nodes]]
  name = "alice"
  command = "polkadot"

  [[relaychain.nodes]]
  name = "bob"
  command = "polkadot"

[[parachains]]
id = 2110
cumulus_based = true


  [[parachains.collator_groups]]
    count = 2
    name = "collator"
    image = "docker.io/mangatasolutions/mangata-node:rococo-latest"
    command = "/mangata/node"
