name: Release

on:
  release:
    types: [published]


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta [kusama]
        id: meta_kusama
        uses: docker/metadata-action@v4.1.1
        with:
          images: docker.io/mangatasolutions/mangata-node
          tags: type=semver,prefix=kusama-,pattern={{ version }}
          flavor: |
            latest=false

      - name: Docker meta [rococo]
        id: meta_rococo
        uses: docker/metadata-action@v4.1.1
        with:
          images: docker.io/mangatasolutions/mangata-node
          tags: type=semver,prefix=rococo-,pattern={{ version }}
          flavor: |
            latest=false

      - name: Tag and push image [kusama]
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          # src: docker.io/mangatasolutions/mangata-node:${{ github.sha }}
          src: docker.io/mangatasolutions/mangata-node:da00cc6a7db7d42fe3f682b3e61ada140dc45634
          dst: ${{ steps.meta_kusama.outputs.tags }}

      - name: Tag and push image [rococo]
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          # src: docker.io/mangatasolutions/mangata-node:${{ github.sha }}
          src: docker.io/mangatasolutions/mangata-node:da00cc6a7db7d42fe3f682b3e61ada140dc45634
          dst: ${{ steps.meta_rococo.outputs.tags }}

      - name: Extract wasms
        run: |
          docker run --entrypoint="" --rm mangatasolutions/mangata-node:da00cc6a7db7d42fe3f682b3e61ada140dc45634 cat /mangata/mangata_kusama_runtime.compact.compressed.wasm > kusama.wasm
          docker run --entrypoint="" --rm mangatasolutions/mangata-node:da00cc6a7db7d42fe3f682b3e61ada140dc45634 cat /mangata/mangata_rococo_runtime.compact.compressed.wasm > rococo.wasm

      - name: Upload wasms to release page
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: "kusama.wasm,rococo.wasm"
